vocab:
    vocab_size: 30000
    coverage: 1
    type: "bpe"
    pad_id: 0
    unk_id: 1
    bos_id: 2
    eos_id: 3
    pad_piece: "[PAD]"
    unk_piece: "[UNK]"
    bos_piece: "[BOS]"
    eos_piece: "[EOS]"


model:
    emb_dim: 256
    hidden_dim: 512
    pff_dim: 512
    n_layers: 3
    n_heads: 8
    dropout_ratio: 0.1


train:
    clip: 1
    n_epochs: 10
    batch_size: 128
    learning_rate: 0.001
    iters_to_accumulate: 4